name: Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DOCKERHUB_USERNAME: nakatatsu

jobs:
  docker-push:
    if: github.event_name == 'push'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set DATE_TAG
        run: echo "DATE_TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build & tag image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/s3-mcp:${{ env.DATE_TAG }} .
          docker tag ${{ env.DOCKERHUB_USERNAME }}/s3-mcp:${{ env.DATE_TAG }} ${{ env.DOCKERHUB_USERNAME }}/s3-mcp:latest

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push date-tagged image
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/s3-mcp:${{ env.DATE_TAG }}

      - name: Push latest tag
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/s3-mcp:latest
